//
//  AgentStateManager.swift
//  leanring-buddy
//
//  External task state manager implementing the core architectural principle:
//  "Task state lives outside the model."
//
//  Owns the task goal, planned subgoals, current progress, compressed action
//  history, and failure counters. Neither the planner nor the actor retains
//  session history; every call reconstructs its prompt freshly from this state.
//

import Combine
import Foundation

/// Status of an individual subgoal in the task plan.
enum AgentSubgoalStatus: String, Codable {
    case pending
    case inProgress
    case completed
    case failed
}

/// A single step in the ordered plan created by the planner model.
struct AgentSubgoal: Identifiable, Codable, Equatable {
    let id: Int
    let description: String
    var status: AgentSubgoalStatus

    init(id: Int, description: String, status: AgentSubgoalStatus = .pending) {
        self.id = id
        self.description = description
        self.status = status
    }
}

/// Manages all state for the currently active automation task outside of the LLM context.
@MainActor
class AgentStateManager: ObservableObject {

    // MARK: - State Properties

    /// The original user instruction / objective.
    @Published private(set) var userGoal: String = ""

    /// The list of subgoals generated by the planner.
    @Published private(set) var orderedSubgoals: [AgentSubgoal] = []

    /// The zero-based index of the currently executing subgoal.
    @Published private(set) var activeSubgoalIndex: Int = 0

    /// Chronological list of compact action-result strings (e.g. "Clicked elem_1 -> Success").
    @Published private(set) var compressedActionHistory: [String] = []

    /// Number of consecutive failures encountered while attempting the current subgoal.
    @Published private(set) var currentSubgoalConsecutiveFailureCount: Int = 0

    /// Context hints retrieved from the local RAG store (past trajectories and UI maps).
    @Published private(set) var retrievedRAGHints: [String] = []

    /// Most recent failure reason if an escalation occurred.
    @Published private(set) var lastEscalationFailureReason: String? = nil

    /// Overall failure reason explaining why the task could not complete.
    @Published private(set) var taskFailureReason: String? = nil

    /// Counter tracking consecutive wait calls to detect and break out of stalled loops.
    private var consecutiveWaitActionCount: Int = 0

    /// Maximum consecutive failures allowed per subgoal before escalating to the planner.
    let maximumConsecutiveFailuresAllowed: Int = 3

    /// Maximum number of recent history lines provided to the actor to keep context compact.
    private let maximumRecentHistoryLinesForActor: Int = 5

    // MARK: - Lifecycle & Initialization

    /// Initializes a new task session with the given user goal and optional RAG hints.
    func initializeTaskSession(userGoal: String, retrievedRAGHints: [String] = []) {
        self.userGoal = userGoal
        self.orderedSubgoals = []
        self.activeSubgoalIndex = 0
        self.compressedActionHistory = []
        self.currentSubgoalConsecutiveFailureCount = 0
        self.retrievedRAGHints = retrievedRAGHints
        self.lastEscalationFailureReason = nil
        self.taskFailureReason = nil
        self.consecutiveWaitActionCount = 0
    }

    /// Sets or replaces the planned subgoals (e.g., at task start or after replanning).
    func updatePlannedSubgoals(with newSubgoals: [AgentSubgoal]) {
        self.orderedSubgoals = newSubgoals
        self.activeSubgoalIndex = 0
        self.currentSubgoalConsecutiveFailureCount = 0
        self.lastEscalationFailureReason = nil
        self.consecutiveWaitActionCount = 0

        if !self.orderedSubgoals.isEmpty {
            self.orderedSubgoals[0].status = .inProgress
        }
    }

    // MARK: - Subgoal & Progress Queries

    /// Returns the currently active subgoal, if any.
    func currentActiveSubgoal() -> AgentSubgoal? {
        guard activeSubgoalIndex >= 0 && activeSubgoalIndex < orderedSubgoals.count else {
            return nil
        }
        return orderedSubgoals[activeSubgoalIndex]
    }

    /// Whether all subgoals in the plan have been successfully marked completed.
    var isTaskCompleted: Bool {
        guard !orderedSubgoals.isEmpty else { return false }
        return orderedSubgoals.allSatisfy { $0.status == .completed }
    }

    // MARK: - Action Recording & Transitions

    /// Records the execution of an action and its result in the compressed history.
    /// Returns `true` if the failure count reached the escalation threshold (`maximumConsecutiveFailuresAllowed`).
    @discardableResult
    func recordActionExecution(
        actionSummary: String,
        resultSummary: String,
        isActionSuccessful: Bool
    ) -> Bool {
        // Detect repeated consecutive wait tool calls to break out of stalls
        let isWaitAction = actionSummary.lowercased().hasPrefix("wait")
        var effectiveActionSuccess = isActionSuccessful

        if isWaitAction {
            consecutiveWaitActionCount += 1
            if consecutiveWaitActionCount >= 2 {
                // Repeated wait without intermediate action indicates stalling
                effectiveActionSuccess = false
                print("⚠️ AgentStateManager: Detected repeated wait loop (\(consecutiveWaitActionCount) in a row). Marking as stalled failure.")
            }
        } else {
            consecutiveWaitActionCount = 0
        }

        let singleLineSummary = "\(actionSummary) -> \(resultSummary)"
        compressedActionHistory.append(singleLineSummary)

        if effectiveActionSuccess {
            // Reset consecutive failure counter on success
            currentSubgoalConsecutiveFailureCount = 0
            return false
        } else {
            // Increment failure count
            currentSubgoalConsecutiveFailureCount += 1
            let failureDetailMessage = consecutiveWaitActionCount >= 2
                ? "Stalled: repeated wait without action. Use run_terminal_command to inspect files/system or escalate."
                : resultSummary

            print("⚠️ AgentStateManager: Failure on subgoal #\(activeSubgoalIndex + 1) (Count: \(currentSubgoalConsecutiveFailureCount)/\(maximumConsecutiveFailuresAllowed))")

            let shouldEscalate = currentSubgoalConsecutiveFailureCount >= maximumConsecutiveFailuresAllowed
            if shouldEscalate {
                lastEscalationFailureReason = "Action failed \(maximumConsecutiveFailuresAllowed) consecutive times: \(failureDetailMessage)"
                taskFailureReason = lastEscalationFailureReason
                DebugEventLogger.shared.log(.escalation(
                    reason: failureDetailMessage,
                    consecutiveFailureCount: currentSubgoalConsecutiveFailureCount
                ))
            }
            return shouldEscalate
        }
    }

    /// Marks the current active subgoal as completed and advances to the next subgoal.
    func completeCurrentActiveSubgoal() {
        guard activeSubgoalIndex < orderedSubgoals.count else { return }

        orderedSubgoals[activeSubgoalIndex].status = .completed
        currentSubgoalConsecutiveFailureCount = 0
        consecutiveWaitActionCount = 0

        activeSubgoalIndex += 1
        if activeSubgoalIndex < orderedSubgoals.count {
            orderedSubgoals[activeSubgoalIndex].status = .inProgress
        }
        print("✅ AgentStateManager: Completed subgoal. Active index is now \(activeSubgoalIndex)/\(orderedSubgoals.count)")
    }

    /// Records an explicit escalation triggered by the actor model.
    func recordExplicitActorEscalation(reason: String) {
        if activeSubgoalIndex < orderedSubgoals.count {
            orderedSubgoals[activeSubgoalIndex].status = .failed
        }
        self.lastEscalationFailureReason = reason
        self.taskFailureReason = reason
        print("🚨 AgentStateManager: Escalation recorded: \(reason)")
    }

    /// Records an overall task failure reason (e.g. step limit reached or unrecoverable error).
    func recordTaskFailure(reason: String) {
        if activeSubgoalIndex < orderedSubgoals.count {
            orderedSubgoals[activeSubgoalIndex].status = .failed
        }
        self.taskFailureReason = reason
        self.lastEscalationFailureReason = reason
        print("❌ AgentStateManager: Task failure recorded: \(reason)")
    }

    // MARK: - Prompt Construction (Stateless Model Invocations)

    /// Constructs a fresh user prompt for the Planner (qwen3.5-9b).
    ///
    /// - Parameter screenSummaryText: Summary of active application, window title, and visible elements.
    func constructPlannerUserPrompt(screenSummaryText: String) -> String {
        var sections: [String] = []

        // User goal
        sections.append("User Goal:\n\(userGoal)")

        // Screen state summary
        sections.append("Current Screen State:\n\(screenSummaryText)")

        // Retrieved RAG hints (past trajectories / UI maps)
        if !retrievedRAGHints.isEmpty {
            let hintsText = retrievedRAGHints.joined(separator: "\n- ")
            sections.append("Retrieved Context & Past Trajectories (treat as hints):\n- \(hintsText)")
        }

        // Failure note if this is a replan invocation
        if let failureReason = lastEscalationFailureReason {
            sections.append("Failure Context (Previous attempt failed, adjust your plan accordingly):\n\(failureReason)")
        }

        return sections.joined(separator: "\n\n")
    }

    /// Constructs user prompt for the initial triage turn of a new task (before subgoals exist).
    func constructActorTriageUserPrompt(currentUIStateText: String) -> String {
        var sections: [String] = []

        // User goal
        sections.append("User Goal:\n\(userGoal)")

        // Current Screen UI State
        sections.append("Current Screen UI State:\n\(currentUIStateText)")

        // RAG hints
        if !retrievedRAGHints.isEmpty {
            let hintsText = retrievedRAGHints.joined(separator: "\n- ")
            sections.append("Retrieved Context & Past Trajectories:\n- \(hintsText)")
        }

        return sections.joined(separator: "\n\n")
    }

    /// Constructs a fresh user prompt for the Actor (qwen3.5-9b).
    ///
    /// - Parameter currentUIStateText: The visible element list (preferred) or screenshot notice.
    func constructActorUserPrompt(currentUIStateText: String) -> String {
        var sections: [String] = []

        // Current subgoal
        let currentSubgoalDescription = currentActiveSubgoal()?.description ?? userGoal
        sections.append("Current Subgoal:\n\(currentSubgoalDescription)")

        // Current UI State
        sections.append("Current UI State:\n\(currentUIStateText)")

        // Compact history: last few actions and results (one line each)
        if compressedActionHistory.isEmpty {
            sections.append("Action History:\n(No actions taken yet for this task)")
        } else {
            let recentHistory = compressedActionHistory.suffix(maximumRecentHistoryLinesForActor)
            let historyText = recentHistory.joined(separator: "\n")
            sections.append("Recent Action History:\n\(historyText)")
        }

        return sections.joined(separator: "\n\n")
    }

    /// Generates a clean text summary of the full trajectory for RAG persistence upon task success.
    func buildCompletedTrajectorySummary() -> String {
        var lines: [String] = []
        lines.append("Goal: \(userGoal)")
        lines.append("Steps taken:")
        for (index, actionLine) in compressedActionHistory.enumerated() {
            lines.append("\(index + 1). \(actionLine)")
        }
        return lines.joined(separator: "\n")
    }
}
